#!/bin/sh
#
# @name NXP HoverGames
#
# @type Quadrotor x
# @class Copter
#
# @output MAIN1 motor 1
# @output MAIN2 motor 2
# @output MAIN3 motor 3
# @output MAIN4 motor 4
#
# @board px4_fmu-v2 exclude
# @board bitcraze_crazyflie exclude
#
# @maintainer Iain Galloway <iain.galloway@nxp.com>
#

. ${R}etc/init.d/rc.mc_defaults

set MIXER quad_x
set PWM_OUT 1234

param set-default IMU_DGYRO_CUTOFF 20
param set-default EKF2_AID_MASK 24
param set-default EKF2_HGT_MODE 3
param set-default EKF2_EV_DELAY 0

# ROLL
param set-default MC_ROLLRATE_D 0.004
param set-default MC_ROLLRATE_FF 0.0
param set-default MC_ROLLRATE_I 0.25
param set-default MC_ROLLRATE_K 0.9
param set-default MC_ROLLRATE_P 0.11
param set-default MC_ROLL_P 3

# PITCH
param set-default MC_PITCHRATE_D 0.004
param set-default MC_PITCHRATE_FF 0.0
param set-default MC_PITCHRATE_I 0.25
param set-default MC_PITCHRATE_K 0.9
param set-default MC_PITCHRATE_P 0.12
param set-default MC_PITCH_P 3

# YAW
param set-default MC_YAWRATE_D 0.0
param set-default MC_YAWRATE_FF 0.0
param set-default MC_YAWRATE_I 0.2
param set-default MC_YAWRATE_K 0.6
param set-default MC_YAWRATE_MAX 45
param set-default MC_YAWRATE_P 0.25
param set-default MC_YAW_P 3.0